/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as AquarioRouteImport } from './routes/aquario'
import { Route as IndexRouteImport } from './routes/index'

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AquarioRoute = AquarioRouteImport.update({
  id: '/aquario',
  path: '/aquario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aquario': typeof AquarioRoute
  '/importar': typeof ImportarRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aquario': typeof AquarioRoute
  '/importar': typeof ImportarRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aquario': typeof AquarioRoute
  '/importar': typeof ImportarRoute
  '/projetos': typeof ProjetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aquario' | '/importar' | '/projetos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aquario' | '/importar' | '/projetos'
  id: '__root__' | '/' | '/aquario' | '/importar' | '/projetos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AquarioRoute: typeof AquarioRoute
  ImportarRoute: typeof ImportarRoute
  ProjetosRoute: typeof ProjetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aquario': {
      id: '/aquario'
      path: '/aquario'
      fullPath: '/aquario'
      preLoaderRoute: typeof AquarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AquarioRoute: AquarioRoute,
  ImportarRoute: ImportarRoute,
  ProjetosRoute: ProjetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
